packages:
  sigs.k8s.io/controller-runtime/pkg/client:
    interfaces:
      Client:
        config:
          dir: "internal/controller"
          filename: "mock_{{.InterfaceName}}_test.go" # _test is added so that it is ignored while calculating test-coverage
  workload.nephio.org/ran_deployment/internal/controller:
    interfaces:
      NfResource:
        config:
          dir: "internal/controller"
          filename: "mock_{{.InterfaceName}}_test.go" # _test is added so that it is ignored while calculating test-coverage
          inpackage: True
