presubmits:
  - name: oai-operator-unit-test
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: golang:1.25-alpine
        command:
        - "/bin/sh"
        - "-c"
        args:
        - |
          apk add --no-cache make bash
          make unit

  - name: oai-operator-lint
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: golangci/golangci-lint:v2.8.0-alpine
        command:
        - "/bin/sh"
        - "-c"
        args:
        - |
          apk add --no-cache make bash
          make lint

  - name: oai-operator-gosec
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: golang:1.25-alpine
        command:
        - "/bin/sh"
        - "-c"
        args:
        - |
          apk add --no-cache make bash git
          make gosec

  - name: oai-operator-license-header-check
    decorate: true
    run_if_changed: "^.*.go$"
    spec:
      containers:
      - image: nephio/gotests:latest
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          "/usr/local/bin/checklicense.sh"

  - name: build-push-pre-image-oai
    cluster: default
    always_run: true
    branches:
    - "main"
    annotations:
      description: Build and Push Presubmit Image to Hub
    decorate: true
    decoration_config:
      censor_secrets: true
    max_concurrency: 0
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:debug
        command:
        - "/bin/sh"
        - "-c"
        - |
          executor --context=${PWD}/ \
            --dockerfile=Dockerfile --destination=nephio/oai-ran-controller:${BUILD_ID}
        volumeMounts:
          - name: kaniko-secret
            mountPath: /kaniko/.docker/
        resources:
          requests:
            cpu: 2
            memory: 2Gi
      volumes:
        - name: kaniko-secret
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json