// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package controller

import (
	"github.com/go-logr/logr"
	"github.com/nephio-project/api/workload/v1alpha1"
	mock "github.com/stretchr/testify/mock"
	v10 "k8s.io/api/apps/v1"
	"k8s.io/api/core/v1"
)

// NewMockNfResource creates a new instance of MockNfResource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNfResource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNfResource {
	mock := &MockNfResource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNfResource is an autogenerated mock type for the NfResource type
type MockNfResource struct {
	mock.Mock
}

type MockNfResource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNfResource) EXPECT() *MockNfResource_Expecter {
	return &MockNfResource_Expecter{mock: &_m.Mock}
}

// GetConfigMap provides a mock function for the type MockNfResource
func (_mock *MockNfResource) GetConfigMap(logger logr.Logger, nFDeployment *v1alpha1.NFDeployment, configInfo *ConfigInfo) []*v1.ConfigMap {
	ret := _mock.Called(logger, nFDeployment, configInfo)

	if len(ret) == 0 {
		panic("no return value specified for GetConfigMap")
	}

	var r0 []*v1.ConfigMap
	if returnFunc, ok := ret.Get(0).(func(logr.Logger, *v1alpha1.NFDeployment, *ConfigInfo) []*v1.ConfigMap); ok {
		r0 = returnFunc(logger, nFDeployment, configInfo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.ConfigMap)
		}
	}
	return r0
}

// MockNfResource_GetConfigMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigMap'
type MockNfResource_GetConfigMap_Call struct {
	*mock.Call
}

// GetConfigMap is a helper method to define mock.On call
//   - logger logr.Logger
//   - nFDeployment *v1alpha1.NFDeployment
//   - configInfo *ConfigInfo
func (_e *MockNfResource_Expecter) GetConfigMap(logger interface{}, nFDeployment interface{}, configInfo interface{}) *MockNfResource_GetConfigMap_Call {
	return &MockNfResource_GetConfigMap_Call{Call: _e.mock.On("GetConfigMap", logger, nFDeployment, configInfo)}
}

func (_c *MockNfResource_GetConfigMap_Call) Run(run func(logger logr.Logger, nFDeployment *v1alpha1.NFDeployment, configInfo *ConfigInfo)) *MockNfResource_GetConfigMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 logr.Logger
		if args[0] != nil {
			arg0 = args[0].(logr.Logger)
		}
		var arg1 *v1alpha1.NFDeployment
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.NFDeployment)
		}
		var arg2 *ConfigInfo
		if args[2] != nil {
			arg2 = args[2].(*ConfigInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNfResource_GetConfigMap_Call) Return(configMaps []*v1.ConfigMap) *MockNfResource_GetConfigMap_Call {
	_c.Call.Return(configMaps)
	return _c
}

func (_c *MockNfResource_GetConfigMap_Call) RunAndReturn(run func(logger logr.Logger, nFDeployment *v1alpha1.NFDeployment, configInfo *ConfigInfo) []*v1.ConfigMap) *MockNfResource_GetConfigMap_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeployment provides a mock function for the type MockNfResource
func (_mock *MockNfResource) GetDeployment(logger logr.Logger, nFDeployment *v1alpha1.NFDeployment, configInfo *ConfigInfo) []*v10.Deployment {
	ret := _mock.Called(logger, nFDeployment, configInfo)

	if len(ret) == 0 {
		panic("no return value specified for GetDeployment")
	}

	var r0 []*v10.Deployment
	if returnFunc, ok := ret.Get(0).(func(logr.Logger, *v1alpha1.NFDeployment, *ConfigInfo) []*v10.Deployment); ok {
		r0 = returnFunc(logger, nFDeployment, configInfo)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v10.Deployment)
		}
	}
	return r0
}

// MockNfResource_GetDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeployment'
type MockNfResource_GetDeployment_Call struct {
	*mock.Call
}

// GetDeployment is a helper method to define mock.On call
//   - logger logr.Logger
//   - nFDeployment *v1alpha1.NFDeployment
//   - configInfo *ConfigInfo
func (_e *MockNfResource_Expecter) GetDeployment(logger interface{}, nFDeployment interface{}, configInfo interface{}) *MockNfResource_GetDeployment_Call {
	return &MockNfResource_GetDeployment_Call{Call: _e.mock.On("GetDeployment", logger, nFDeployment, configInfo)}
}

func (_c *MockNfResource_GetDeployment_Call) Run(run func(logger logr.Logger, nFDeployment *v1alpha1.NFDeployment, configInfo *ConfigInfo)) *MockNfResource_GetDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 logr.Logger
		if args[0] != nil {
			arg0 = args[0].(logr.Logger)
		}
		var arg1 *v1alpha1.NFDeployment
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.NFDeployment)
		}
		var arg2 *ConfigInfo
		if args[2] != nil {
			arg2 = args[2].(*ConfigInfo)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNfResource_GetDeployment_Call) Return(deployments []*v10.Deployment) *MockNfResource_GetDeployment_Call {
	_c.Call.Return(deployments)
	return _c
}

func (_c *MockNfResource_GetDeployment_Call) RunAndReturn(run func(logger logr.Logger, nFDeployment *v1alpha1.NFDeployment, configInfo *ConfigInfo) []*v10.Deployment) *MockNfResource_GetDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// GetService provides a mock function for the type MockNfResource
func (_mock *MockNfResource) GetService() []*v1.Service {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetService")
	}

	var r0 []*v1.Service
	if returnFunc, ok := ret.Get(0).(func() []*v1.Service); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.Service)
		}
	}
	return r0
}

// MockNfResource_GetService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetService'
type MockNfResource_GetService_Call struct {
	*mock.Call
}

// GetService is a helper method to define mock.On call
func (_e *MockNfResource_Expecter) GetService() *MockNfResource_GetService_Call {
	return &MockNfResource_GetService_Call{Call: _e.mock.On("GetService")}
}

func (_c *MockNfResource_GetService_Call) Run(run func()) *MockNfResource_GetService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNfResource_GetService_Call) Return(services []*v1.Service) *MockNfResource_GetService_Call {
	_c.Call.Return(services)
	return _c
}

func (_c *MockNfResource_GetService_Call) RunAndReturn(run func() []*v1.Service) *MockNfResource_GetService_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceAccount provides a mock function for the type MockNfResource
func (_mock *MockNfResource) GetServiceAccount() []*v1.ServiceAccount {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetServiceAccount")
	}

	var r0 []*v1.ServiceAccount
	if returnFunc, ok := ret.Get(0).(func() []*v1.ServiceAccount); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1.ServiceAccount)
		}
	}
	return r0
}

// MockNfResource_GetServiceAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceAccount'
type MockNfResource_GetServiceAccount_Call struct {
	*mock.Call
}

// GetServiceAccount is a helper method to define mock.On call
func (_e *MockNfResource_Expecter) GetServiceAccount() *MockNfResource_GetServiceAccount_Call {
	return &MockNfResource_GetServiceAccount_Call{Call: _e.mock.On("GetServiceAccount")}
}

func (_c *MockNfResource_GetServiceAccount_Call) Run(run func()) *MockNfResource_GetServiceAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNfResource_GetServiceAccount_Call) Return(serviceAccounts []*v1.ServiceAccount) *MockNfResource_GetServiceAccount_Call {
	_c.Call.Return(serviceAccounts)
	return _c
}

func (_c *MockNfResource_GetServiceAccount_Call) RunAndReturn(run func() []*v1.ServiceAccount) *MockNfResource_GetServiceAccount_Call {
	_c.Call.Return(run)
	return _c
}

// createNetworkAttachmentDefinitionNetworks provides a mock function for the type MockNfResource
func (_mock *MockNfResource) createNetworkAttachmentDefinitionNetworks(s string, nFDeploymentSpec *v1alpha1.NFDeploymentSpec) (string, error) {
	ret := _mock.Called(s, nFDeploymentSpec)

	if len(ret) == 0 {
		panic("no return value specified for createNetworkAttachmentDefinitionNetworks")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *v1alpha1.NFDeploymentSpec) (string, error)); ok {
		return returnFunc(s, nFDeploymentSpec)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *v1alpha1.NFDeploymentSpec) string); ok {
		r0 = returnFunc(s, nFDeploymentSpec)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, *v1alpha1.NFDeploymentSpec) error); ok {
		r1 = returnFunc(s, nFDeploymentSpec)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNfResource_createNetworkAttachmentDefinitionNetworks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'createNetworkAttachmentDefinitionNetworks'
type MockNfResource_createNetworkAttachmentDefinitionNetworks_Call struct {
	*mock.Call
}

// createNetworkAttachmentDefinitionNetworks is a helper method to define mock.On call
//   - s string
//   - nFDeploymentSpec *v1alpha1.NFDeploymentSpec
func (_e *MockNfResource_Expecter) createNetworkAttachmentDefinitionNetworks(s interface{}, nFDeploymentSpec interface{}) *MockNfResource_createNetworkAttachmentDefinitionNetworks_Call {
	return &MockNfResource_createNetworkAttachmentDefinitionNetworks_Call{Call: _e.mock.On("createNetworkAttachmentDefinitionNetworks", s, nFDeploymentSpec)}
}

func (_c *MockNfResource_createNetworkAttachmentDefinitionNetworks_Call) Run(run func(s string, nFDeploymentSpec *v1alpha1.NFDeploymentSpec)) *MockNfResource_createNetworkAttachmentDefinitionNetworks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *v1alpha1.NFDeploymentSpec
		if args[1] != nil {
			arg1 = args[1].(*v1alpha1.NFDeploymentSpec)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNfResource_createNetworkAttachmentDefinitionNetworks_Call) Return(s1 string, err error) *MockNfResource_createNetworkAttachmentDefinitionNetworks_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *MockNfResource_createNetworkAttachmentDefinitionNetworks_Call) RunAndReturn(run func(s string, nFDeploymentSpec *v1alpha1.NFDeploymentSpec) (string, error)) *MockNfResource_createNetworkAttachmentDefinitionNetworks_Call {
	_c.Call.Return(run)
	return _c
}
