/*
Copyright 2026 The Nephio Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// crdBaseDir is where controller-gen is pointed at by the manifests target.
const crdBaseDir = "../../config/crd/bases"

// expectedCRDs is the complete set of CRDs controller-gen may emit into
// crdBaseDir. It is the contract for this generator's output, not a
// repository-wide scan for CustomResourceDefinition manifests.
//
// It is empty on purpose. The types in this package are payloads decoded out of
// NFConfig.spec.configRefs, not Kubernetes resources, and the API server serves
// the aggregate NFConfig CRD from nephio-project/api instead. Adding an entry
// here is an API decision, not a code generation detail: a resource needs an
// owner group, scheme registration, RBAC, an installation path, a controller
// that watches it and a compatibility story for the payloads already shipped in
// catalog. Until all of that exists, generating a CRD only publishes an API that
// nothing serves.
var expectedCRDs = map[string]struct{}{}

// TestCRDInventory checks that the committed CRDs are exactly the ones this
// repository claims to own.
//
// A stale manifest is not hypothetical here: the underscore-prefixed CRDs with
// an empty group and an empty version were generated by an earlier toolchain
// bump and survived in the tree because controller-gen never deletes an
// artifact it has stopped emitting.
func TestCRDInventory(t *testing.T) {
	entries, err := os.ReadDir(crdBaseDir)
	if os.IsNotExist(err) {
		entries = nil
	} else {
		require.NoError(t, err)
	}

	found := map[string]struct{}{}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".yaml" {
			continue
		}
		found[entry.Name()] = struct{}{}
	}

	for name := range found {
		_, expected := expectedCRDs[name]
		assert.True(t, expected,
			"%s is not in expectedCRDs; publishing a CRD is an API decision, see the comment there", name)
	}
	for name := range expectedCRDs {
		_, present := found[name]
		assert.True(t, present, "%s is expected but was not generated", name)
	}
}
